name: deploy hook site
on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        working-directory: ./
        run: |
          npm ci --no-progress
          npm run build
      - uses: amondnet/vercel-action@v20.0.1
        id: vercel-action
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--confirm"
      - name: preview-url
        run: | 
          echo ${{ steps.vercel-action.outputs.preview-url }}
        

